openapi: 3.1.0
info:
  title: Zoo Safari Booking API
  description: API for managing bookings and tours in a fictional safari park in the Serengeti region.
  version: 1.0.0
servers:
  - url: https://api.zoosafari.fake/v1
paths:
  /bookings:
    get:
      summary: List all bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
    post:
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBooking'
      responses:
        '201':
          description: Booking created
  /bookings/{bookingId}:
    get:
      summary: Get a specific booking
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details
    put:
      summary: Modify an existing booking
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBooking'
      responses:
        '200':
          description: Booking updated
    delete:
      summary: Cancel a booking
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Booking cancelled
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
        tourType:
          type: string
          enum: [individual, group]
        date:
          type: string
          format: date
        guests:
          type: integer
        status:
          type: string
          enum: [confirmed, cancelled, pending]
    NewBooking:
      type: object
      required: [tourType, date, guests]
      properties:
        tourType:
          type: string
        date:
          type: string
          format: date
        guests:
          type: integer
    UpdateBooking:
      type: object
      properties:
        date:
          type: string
          format: date
        guests:
          type: integer
